services:
  - type: web
    name: ai-journal-companion
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.8.0
      - key: GEMINI_API_KEY
        sync: false 